### ISSUE TITLE
What is 'plus' called?

### ISSUE THREAD

**Issue by jayveedee** [iberianpig/fusuma-plugin-sendkey#10]
Trying to add a zoom in and out gesture by using `left ctrl & +` and `left ctrl & -` but am unable to find the normal '+' key, however I found '-' easily. There is KPPLUS but that's it.
Also I know that you can also use `left ctrl & scrollup` and `left ctrl & scrolldown` but this is mostly application based, whereas the other gesture works pretty much every where I want it to work :)
![image](https://user-images.githubusercontent.com/24821250/87509079-18543f80-c671-11ea-955b-8239490fbb32.png)

**Comment by iberianpig** [comment]
See this link. (https://github.com/iberianpig/fusuma-plugin-sendkey/issues/4)

Evdev is a near hardware layer. Therefore, Evdev treats that Equal key and Plus key are same physical key.

**Comment by jayveedee** [comment]
> See this link. (#4)
> 
> Evdev is a near hardware layer. Therefore, Evdev treats that Equal key and Plus key are same physical key.

Thanks! That solved it :)
