### ISSUE TITLE
Missing instruction to install: plugin needs "build-essential" package

### ISSUE THREAD

**Issue by SamuXzX** [iberianpig/fusuma-plugin-sendkey#11]
This is just an advice on what writing in the README.md: I tried installing the plugin and got the error `make failed, exit code 127`. A quick search on Stackoverflow tells you that "build-essential" package needs to be installed in order to build the gem native estension.
It would be useful to write it within "Install the dependencies".

**Comment by iberianpig** [comment]
Thank you for reporting!
