### ISSUE TITLE
1 second delay before keys are fired

### ISSUE THREAD

**Issue by v4dkou** [iberianpig/fusuma-plugin-sendkey#14]
Trying out pinch-to-zoom gestures with Fusuma on Fedora 32 (Gnome 3.36.5, Wayland)

Logs appear to show up pretty fast right after I do the gesture, but the actual input happens after almost a second of delay.
```I, [2020-12-27T16:38:29.022197 #423575]  INFO -- : {:command=>"fusuma-sendkey LEFTCTRL+KPMINUS"}
I, [2020-12-27T16:38:29.123489 #423575]  INFO -- : {:command=>"fusuma-sendkey LEFTCTRL+KPMINUS"}
I, [2020-12-27T16:38:29.224947 #423575]  INFO -- : {:command=>"fusuma-sendkey LEFTCTRL+KPMINUS"}
I, [2020-12-27T16:38:29.325804 #423575]  INFO -- : {:command=>"fusuma-sendkey LEFTCTRL+KPMINUS"}
I, [2020-12-27T16:38:34.230984 #423575]  INFO -- : {:command=>"fusuma-sendkey LEFTCTRL+KPPLUS"}
I, [2020-12-27T16:38:34.332306 #423575]  INFO -- : {:command=>"fusuma-sendkey LEFTCTRL+KPPLUS"}
```

`~/.config/fusuma/config.yml` :
```pinch:
  in:
    command: "fusuma-sendkey LEFTCTRL+KPPLUS" # Zoom in
    threshold: 0.1
  out:
    command: "fusuma-sendkey LEFTCTRL+KPMINUS" # Zoom out
    threshold: 0.1
```

**Comment by iberianpig** [comment]
Did you try setting interval?

**Comment by v4dkou** [comment]
@iberianpig If you are talking about _fusuma_'s interval setting, I actually have the problem even just running the raw CLI command `fusuma-sendkey KPPLUS`, it just takes a second to write the plus sign.

Are there any logs that might help you figuring it out?

**Comment by iberianpig** [comment]
I noticed your setting is using `command:`
Could you try the following setting? (use `sendkey: ` instead of `command:`)

```yaml
  in:
    sendkey: LEFTCTRL+KPPLUS # Zoom in
    threshold: 0.1
  out:
    sendkey: LEFTCTRL+KPMINUS # Zoom out
    threshold: 0.1
```

**Comment by paragmhatre10** [comment]
I had this issue with 'command'. Changing it to 'sendkey' solved this for me. 

But, in terminal when I manually type the command, it has a delay to execute the action. Do we know the reason for that?

**Comment by iberianpig** [comment]
When run from a terminal, bin/exe/fusuma-sendkey will be executed in the following flow.

1) Get a list of devices with the libinput list-device command.
2) Search for the keyboard device.
3) Send a key with the keyboard device.

(1) is almost all the time needed to run $fusuma-sendkey in the terminal.

When SendkeyExecutor runs from Fusuma, the time cost of processing (1) and (2), which are done at startup, will be zero. Therefore, keyboard emulation can be done with zero delay.

**Comment by iberianpig** [comment]
```
[LineProf] ===============================================================

exe/fusuma-sendkey
               |  44
               |  45  profile = lineprof(%r{#{Pathname.new(__FILE__).parent.parent}/.}) do
 436.9ms     2 |  46    keyboard = Fusuma::Plugin::Sendkey::Keyboard.new
   0.4ms     2 |  47    keyboard.valid?(param: param) && keyboard.type(param: param)
               |  48  end
               |  49  LineProf.report(profile)

lib/fusuma/plugin/sendkey/keyboard.rb
               |  13          def initialize(name_pattern: nil)
               |  14            name_pattern ||= 'keyboard|Keyboard|KEYBOARD'
 436.8ms     1 |  15            device = find_device(name_pattern: name_pattern)
               |  16
               |  17            if device.nil?
```
