### ISSUE TITLE
Super is not supported

### ISSUE THREAD

**Issue by kushats** [iberianpig/fusuma-plugin-sendkey#17]
Unfortunately, I find that super is not supported. So the combo with super + s, super + d, and others are unavailable. 
Can you please add it?  

Or maybe I can do something instead of workspace and window managing [here](https://github.com/iberianpig/fusuma-plugin-wmctrl)?

**Comment by iberianpig** [comment]
You can use `LEFTMETA` or `RIGHTMETA`

```
$ fusuma-sendkey -l | grep -i meta
LEFTMETA
RIGHTMETA
$ fusuma-sendkey LEFTMETA
```
