### ISSUE TITLE
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

### ISSUE THREAD

**Issue by Swoy** [iberianpig/fusuma-plugin-sendkey#3]
When trying to install this gem as instructed in README.md, I get the following error:
```
Building native extensions. This could take a while...
ERROR:  Error installing fusuma-plugin-sendkey:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/revdev-0.2.1/ext/revdev
/usr/bin/ruby2.5 -r ./siteconf20200326-10985-1m7ckai.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/revdev-0.2.1 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/revdev-0.2.1/gem_make.out
```
Is there some dependencies that is required in the Ruby installation?

**Comment by Wonder2018** [comment]
> 尝试按README.md中的指示安装此gem时，出现以下错误：
> 
> ```
> Building native extensions. This could take a while...
> ERROR:  Error installing fusuma-plugin-sendkey:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /var/lib/gems/2.5.0/gems/revdev-0.2.1/ext/revdev
> /usr/bin/ruby2.5 -r ./siteconf20200326-10985-1m7ckai.rb extconf.rb
> mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /var/lib/gems/2.5.0/gems/revdev-0.2.1 for inspection.
> Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/revdev-0.2.1/gem_make.out
> ```
> 
> Ruby安装中是否需要一些依赖项？

try this:
sudo apt install ruby-dev
or
sudo yum install ruby-devel

**Comment by yunus-emre-zengin** [comment]
@Wonder2018 thank you so much, I had this problem too and my problem is fixed now.

**Comment by iberianpig** [comment]
Thanks for solving this issue!
Added ruby-dev installation to README.
