### ISSUE TITLE
SUPER key

### ISSUE THREAD

**Issue by mutalibmohammed** [iberianpig/fusuma-plugin-sendkey#7]
I'm unable to find the the SUPER key in the list of keys. I cannot find the underscore key as well, perhaps it has a different name?

You can see the output for the fusuma-sendkey -l here: https://pastebin.com/9E4L9Qjf

**Comment by iberianpig** [comment]
@mutalibmohammed 
Yes, SUPER key is LEFTMETA or RIGHTMETA key in fusuma-pluigin-sendkey (evdev)

```
$ fusuma-sendkey -l | grep META
LEFTMETA
RIGHTMETA
```
